import {
  ArrowLeftRight,
  BadgeCheck,
  Box,
  Cable,
  CalendarDays,
  CheckCheck,
  ClipboardCheck,
  Construction,
  Droplets,
  FileCheck2,
  FileText,
  IndianRupee,
  Link,
  ListChecks,
  MapPin,
  MessageSquare,
  MessageSquareWarning,
  RefreshCcw,
  Ruler,
  Signpost,
  UserCheck,
} from 'lucide-react-native';

import type { SupervisorStatId } from '@/services/mobileStats';

export const statIcons: Record<SupervisorStatId, typeof ClipboardCheck> = {
  'survey-done': ClipboardCheck,
  'conversion-done': RefreshCcw,
  'gi-done': Ruler,
  'jmr-done': FileCheck2,
  'gc-done': Cable,
  'site-expenses-done': IndianRupee,
  laying: Construction,
  'flushing-testing': Droplets,
  'valve-chamber': Box,
  'pre-commissioning': ListChecks,
  commissioning: BadgeCheck,
  dpr: FileText,
  planning: CalendarDays,
  'pole-marker': Signpost,
  'route-marker': MapPin,
  'complaint-customer': MessageSquareWarning,
  'total-pbg-assignment': UserCheck,
  'total-connection-done': Link,
  'total-connection-remark': MessageSquare,
  'total-conversion-done': ArrowLeftRight,
  'customer-resolve': CheckCheck,
};
